### PR TITLE
[OCU-89] change registry from docker to github

### PR DESCRIPTION
**Pull request by northdpole**

### CODE REVIEW

**Comment by ptzianos** [comment]
Can you please create a ticket for this?

**Comment by ptzianos** [comment]
can you add the ticket to the commit message please?

**Comment by ptzianos** [comment]
@northdpole can you please rebase this on the latest main? there's a lot of noise atm from the changes in the main's commit history

**Comment by northdpole** [comment]
done @ptzianos

**Review by ptzianos — APPROVED** [review]

**Pull request merged**
